---

- name: stop and disable tinc
  service:
    name: tinc
    enabled: no
    state: stopped
    pattern: "tincd -n {{ tinc_netname }}"

- name: delete tinc netname directory
  file:
    path: "/etc/tinc/{{ tinc_netname }}"
    state: absent

- name: delete nets.boot
  file:
    path: /etc/tinc/nets.boot
    state: absent
